---
title: "demographics"
format: html
---

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
load_ukb_vols <- function(dataset) {
  arrow::open_dataset(dataset) |>
    dplyr::rename_with(~stringr::str_c("f.", .x) |> stringr::str_replace("-", ".")) |>
    dplyr::filter(!is.na("25733-2.0")) |> # get "usable" scans; https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind1807&L=UKB-NEUROIMAGING&D=0&P=1613
    dplyr::select(
      f.eid, 
      sex = f.31.0.0,
      age = f.21003.2.0,
      t1_motion=f.24419.2.0,
      acq_day = f.53.2.0,
      head_size = f.25000.2.0,
      icv = f.26521.2.0,
      site=f.54.2.0,
      tidyselect::matches("(25011|25012|25013|25014|25015|25016|25017|25018|25019|25020|25021|25022|25023|25024)\\.2"),
      tidyselect::matches("(26558|26589)\\.2"), # ASEG thalamus-proper
      tidyselect::matches("(26559|26590)\\.2"), # ASEG caudate
      tidyselect::matches("(26560|26591)\\.2"), # ASEG putamen
      tidyselect::matches("(26561|26592)\\.2"), # ASEG pallidum
      tidyselect::matches("(26562|26593)\\.2"), # ASEG hippocampus
      tidyselect::matches("(26563|26594)\\.2"), # ASEG amygdala
      tidyselect::matches("(26564|26595)\\.2"), # ASEG accumbens
      tidyselect::matches("(26714|26715)\\.2"), # FS SUBSEG whole-thalamus
      tidyselect::matches("(26641|26663)\\.2"), # FS SUBSEG whole-hippocampus
      tidyselect::matches("(26609|26619)\\.2") # FS SUBSEG whole-amygdala
    ) |>
    na.omit() |>
    dplyr::collect() |>
    tidyr::pivot_longer(
      c(-f.eid, -sex, -age, -t1_motion, -acq_day, -head_size, -icv, -site)) |>
    dplyr::mutate(
      hemisphere = dplyr::case_when(
        stringr::str_detect(
          name, 
          "25011|25013|25015|25017|25019|25021|25023|26714|26641|26609|26558|26559|26560|26561|26562|26563|26564"
        ) ~ "Left",
        TRUE ~ "Right"
      ),
      source = dplyr::case_when(
        stringr::str_detect(name, "26714|26715|26641|26663|6609|26619") ~ "FSSUBSEG",
        stringr::str_detect(
          name, 
          "25011|25012|25013|25014|25015|25016|25017|25018|25019|25020|25021|25022|25023|25024"
        ) ~ "FIRST",
        TRUE ~ "FreeSurfer"
      ),
      StructName = dplyr::case_when(
        stringr::str_detect(name, "25011|25012|26558|26589|26714|26715") ~ "Thalamus",
        stringr::str_detect(name, "25013|25014|26559|26590") ~ "Caudate",
        stringr::str_detect(name, "25015|25016|26560|26591") ~ "Putamen",
        stringr::str_detect(name, "25017|25018|26561|26592") ~ "Pallidum",
        stringr::str_detect(name, "25019|25020|26562|26593|26641|26663") ~"Hippocampus",
        stringr::str_detect(name, "25021|25022|26563|26594|26609|26619") ~ "Amygdala",
        stringr::str_detect(name, "25023|25024|26564|26595") ~ "Accumbens"
      ),
      instance = stringr::str_extract(name, ".([23]).", group=1),
      value = value / 1000
    ) |>
    dplyr::select(-name, -instance) |>
    tidyr::unite(Structure, c(hemisphere, StructName, source)) |>
    tidyr::pivot_wider(names_from = Structure) |>
    na.omit() |>
    dplyr::select(-tidyselect::ends_with("FSSUBSEG"))
}
```


```{r}
hcp <- readr::read_csv("data/HCP1200.csv") |>
  rename(sub=Subject)

hcp2 <- readr::read_csv("data/RESTRICTED_martin_2_5_2024_10_18_28.csv") |>
  rename(sub=Subject)

hcp_motion <- arrow::open_dataset("/Users/psadil/Desktop/motion_tmp/hcps12000.parquet") |>
  group_by(sub, ped, task, ses) |>
  summarise(fd = mean(fd)) |>
  collect() |>
  left_join(hcp) |>
  left_join(hcp2) 
```


```{r}

hcp_motion  |>
  crossing(fd_thresh = seq(0.1, 1, by=0.1)) |>
  mutate(exclude = fd > fd_thresh) |>
  summarise(
    exclude = mean(exclude),
    .by = (fd_thresh)) |>
  mutate(fd_thresh = factor(fd_thresh)) |>
  ggplot(aes(x = fd_thresh, y = exclude)) +
  geom_bar() +
  ylim(0, 1)

```





```{r}

hcp_motion  |>
  crossing(fd_thresh = seq(0.1, 1, by=0.1)) |>
  mutate(exclude = fd > fd_thresh) |>
  summarise(
    exclude = mean(exclude),
    .by = c(fd_thresh, Gender)) |>
  mutate(fd_thresh = factor(fd_thresh)) |>
  ggplot(aes(x = fd_thresh, y = exclude, fill=Gender)) +
  geom_col(position = "dodge") +
  ylim(0, 1)

```




```{r}

hcp_motion  |>
  crossing(fd_thresh = seq(0.1, 1, by=0.1)) |>
  mutate(exclude = fd > fd_thresh) |>
  summarise(
    exclude = mean(exclude),
    .by = c(fd_thresh, Age)) |>
  mutate(fd_thresh = factor(fd_thresh)) |>
  ggplot(aes(x = fd_thresh, y = exclude, fill=Age)) +
  geom_col(position = "dodge") +
  ylim(0, 1)

```



```{r}

hcp_motion  |>
  ggplot(aes(x = Age_in_Yrs, y = fd, color=Gender)) +
  geom_point()

```


```{r}

Gender <- hcp_motion |>
  ungroup() |>
  crossing(fd_thresh = seq(0.1, 0.5, by=0.1)) |>
  mutate(exclude = fd > fd_thresh) |>
  summarise(
    exclude = mean(exclude),
    .by = c(fd_thresh, Gender)) |>
  mutate(fd_thresh = factor(fd_thresh)) |>
  ggplot(aes(fill=Gender, y=exclude, x=fd_thresh)) +
  geom_col(position = "dodge")  +
  ylim(0,1)

BMI <- hcp_motion |>
  ungroup() |>
  filter(!is.na(BMI)) |>
  mutate(
    BMI = cut(
      BMI, 
      breaks = c(0, 18.5, 25, 30, 35, 40, Inf),
      levels = c("underweight", "healthy", "overweight", "obese", "obese2", "obese3"))) |>
  crossing(fd_thresh = seq(0.1, 0.5, by=0.1)) |>
  mutate(exclude = fd > fd_thresh) |>
  summarise(
    exclude = mean(exclude),
    .by = c(fd_thresh, BMI)) |>
  mutate(fd_thresh = factor(fd_thresh)) |>
  ggplot(aes(x=fd_thresh, y=exclude, fill=BMI)) +
  geom_col(position = "dodge")  +
  ylim(0,1)


Age <- hcp_motion |>
  ungroup() |>
  crossing(fd_thresh = seq(0.1, 0.5, by=0.1)) |>
  mutate(exclude = fd > fd_thresh) |>
  summarise(
    exclude = mean(exclude),
    .by = c(fd_thresh, Age)) |>
  mutate(fd_thresh = factor(fd_thresh)) |>
  ggplot(aes(x=fd_thresh, y=exclude, fill=Age)) +
  geom_col(position = "dodge")  +
  ylim(0,1)

BloodPressure <- hcp_motion |>
  ungroup() |>
  filter(!is.na(BPSystolic)) |>
  crossing(fd_thresh = seq(0.1, 0.5, by=0.1)) |>
  mutate(
    BPDiastolic = cut(
      BPDiastolic, 
      breaks = c(0, 60, 80, 90, 120, Inf))) |>
  mutate(exclude = fd > fd_thresh) |>
  summarise(
    exclude = mean(exclude),
    .by = c(fd_thresh, BPDiastolic)) |>
  mutate(fd_thresh = factor(fd_thresh)) |>
  ggplot(aes(x=fd_thresh, y=exclude, fill=BPDiastolic)) +
  geom_col(position = "dodge") +
  ylim(0,1)


Gender + BMI + Age + BloodPressure + plot_layout(nrow = 2)

```



```{r}

ukb <- load_ukb_vols("/Users/psadil/git/manuscripts/auto-volume-comparisons/data/ukb677207_bulk.parquet") |> select(-starts_with("Left"), -starts_with("Right"))

```




