#!/bin/bash

#  prep destinations
for d in abcd hcpya hcpa hcpd ukb spacetop; do
	dst=sourcedata/$d
	if [[ ! -d $dst ]]; then
		mkdir -p ${dst}
	fi
done

# Gather motion files

## HCP
find \
	/dcs07/smart/data/human-connectome-project-openaccess/HCP1200 \
	-mindepth 5 \
	-maxdepth 5 \
	-name "*Movement_*.txt" \
	-xtype f \
	-exec cp \
	-Lsv --parents {} sourcedata/hcpya/ \;

find \
	/dcs07/smart/data/HCPDevelopmentRec/sourcedata/fmriresults01 \
	-mindepth 5 \
	-maxdepth 5 \
	-name "*Movement_*.txt" \
	-type f \
	-exec cp -sv --parents {} sourcedata/hcpd/ \;

find \
	/dcs07/smart/data/HCPAgingRec/sourcedata/fmriresults01 \
	-mindepth 5 \
	-maxdepth 5 \
	-name "*Movement_*.txt" \
	-type f \
	-exec cp -sv --parents {} sourcedata/hcpa/ \;

## ABCD
find \
	/dcs07/smart/data/abcd/rawdata \
	-mindepth 4 \
	-maxdepth 4 \
	-name "*motion.tsv" \
	-type f \
	-exec cp -uv --parents {} sourcedata/abcd/ \;

## UKB
ukb_srcs=sourcedata/ukb_srcs
find /dcs07/smart/data/ukb/rawdata/ -maxdepth 1 -type d -name "sub*" >$ukb_srcs
n_ukb=$(wc -l $ukb_srcs | cut -f 1 -d " ")

ukb_motion_files=sourcedata/ukb_motion_files
for i in $(seq 1 "${n_ukb}"); do
	sub=$(sed "${i}q;d" $ukb_srcs)
	echo "${i}"
	echo "${sub}"
	for ses in "${sub}"/ses*; do
		mcf_task=${ses}/non-bids/20249/fMRI/tfMRI.feat/mc/prefiltered_func_data_mcf.par
		if [[ -e $mcf_task ]]; then
			echo "${mcf_task}" >>$ukb_motion_files
		fi
		rms_task=${ses}/non-bids/20249/fMRI/tfMRI.feat/mc/prefiltered_func_data_mcf_rel.rms
		if [[ -e $rms_task ]]; then
			echo "${rms_task}" >>$ukb_motion_files
		fi
		mcf_rest=${ses}/non-bids/20227/fMRI/rfMRI.ica/mc/prefiltered_func_data_mcf.par
		if [[ -e $mcf_rest ]]; then
			echo "${mcf_rest}" >>$ukb_motion_files
		fi
		rms_rest=${ses}/non-bids/20227/fMRI/rfMRI.ica/mc/prefiltered_func_data_mcf_rel.rms
		if [[ -e $rms_rest ]]; then
			echo "${rms_rest}" >>$ukb_motion_files
		fi
	done
done

cp $ukb_motion_files $ukb_motion_files.bak

sed 's#/dcs07/smart/data/ukb/rawdata/##' $ukb_motion_files.bak >$ukb_motion_files

cat $ukb_motion_files |
	xargs -I % cp --parents -vsL /dcs07/smart/data/ukb/rawdata/% sourcedata/ukb/

# spacetop is handled within gather

# Aggregate Motion

pixi run python hcp.py \
	sourcedata/hcpya/dcs07/smart/data/human-connectome-project-openaccess/HCP1200 \
	derivatives/premotion/dataset=hcpya \
	--sessions /dcs07/smart/data/human-connectome-project-openaccess/sourcedata/sessionSummaryCSV_1200Release

pixi run python hcp.py \
	sourcedata/hcpa/dcs07/smart/data/HCPAgingRec/sourcedata/fmriresults01 \
	derivatives/premotion/dataset=hcpa

pixi run python hcp.py \
	sourcedata/hcpd/dcs07/smart/data/HCPDevelopmentRec/sourcedata/fmriresults01 \
	derivatives/premotion/dataset=hcpd

pixi run python abcd.py sourcedata/abcd/dcs07/smart/data/abcd/rawdata derivatives/premotion/dataset=abcd
pixi run python ukb.py sourcedata/ukb/dcs07/smart/data/ukb/rawdata derivatives/premotion/dataset=ukb

# (needs 256 Gb memory)
pixi run python gather.py

# events
find \
	/dcs07/smart/data/HCPAgingRec/sourcedata/fmriresults01 \
	-mindepth 5 \
	-maxdepth 5 \
	-type d \
	-name EVs \
	-exec cp -av --parents {} HCPAgingRec/ \;

find \
	/dcs07/smart/data/abcd/rawdata \
	-mindepth 4 \
	-maxdepth 4 \
	-name "*events.tsv" \
	-type f \
	-exec cp -uv --parents {} abcd/ \;
