#!/bin/bash

# Gather motion files

## HCP
find \
  /dcs07/smart/data/human-connectome-project-openaccess/HCP1200 \
  -mindepth 5 \
  -maxdepth 5 \
  -name "*Movement_Regressors.txt" \
  -xtype f \
  -exec cp \
  -Lv --parents {} ./ \;

find \
  /dcs07/smart/data/HCPDevelopmentRec/sourcedata/fmriresults01 \
  -mindepth 5 \
  -maxdepth 5 \
  -name "*Movement_Regressors.txt" \
  -type f \
  -exec cp -v --parents {} ./ \;

find \
  /dcs07/smart/data/HCPAgingRec/sourcedata/fmriresults01 \
  -mindepth 5 \
  -maxdepth 5 \
  -name "*Movement_Regressors.txt" \
  -type f \
  -exec cp -v --parents {} ./ \;

## ABCD
find \
  /dcs07/smart/data/abcd/rawdata \
  -mindepth 4 \
  -maxdepth 4 \
  -name "*motion.tsv" \
  -type f \
  -exec cp -uv --parents {} ./ \;


## UKB
find /dcs07/smart/data/ukb/rawdata/ -maxdepth 1 -type d -name "sub*" > ukb_srcs
n_ukb=$(wc -l ukb_srcs | cut -f 1 -d " ")

for i in $(seq 1 "${n_ukb}" ); do
    sub=$(sed "${i}q;d" ukb_srcs)
    echo "${i}"
    echo "${sub}"
    for ses in "${sub}"/ses*; do
        mcf_task=${ses}/non-bids/20249/fMRI/tfMRI.feat/mc/prefiltered_func_data_mcf.par
        if [[ -e $mcf_task ]]; then
            echo $mcf_task >> ukb_motion_files
        fi
        rms_task=${ses}/non-bids/20249/fMRI/tfMRI.feat/mc/prefiltered_func_data_mcf_rel.rms
        if [[ -e $rms_task ]]; then
            echo $rms_task >> ukb_motion_files
        fi
        mcf_rest=${ses}/non-bids/20227/fMRI/rfMRI.ica/mc/prefiltered_func_data_mcf.par
        if [[ -e $mcf_rest ]]; then
            echo ${mcf_rest} >> ukb_motion_files
        fi
        rms_rest=${ses}/non-bids/20227/fMRI/rfMRI.ica/mc/prefiltered_func_data_mcf_rel.rms
        if [[ -e $rms_rest ]]; then
            echo ${rms_rest} >> ukb_motion_files
        fi
    done
done 

cp ukb_motion_files ukb_motion_files.bak

sed 's#/dcs07/smart/data/ukb/rawdata/##' ukb_motion_files.bak > ukb_motion_files

cat ukb_motion_files \
    | xargs -I % cp --parents -vL /dcs07/smart/data/ukb/rawdata/% ./


## SpaceTop

find \
  /dcs04/smart/data/spatialtopology/fmriprep/results/fmriprep \
  -name "*timeseries.tsv" \
  -exec cp -uv --parents {} ./ \;

# Aggregate Motion

python hcp.py \
  sourcedata/motion/human-connectome-project-openaccess/dcs07/smart/data/human-connectome-project-openaccess/HCP1200 \
  derivatives/motion/dataset=human-connectome-project-openaccess \
  --sessions sourcedata/sessionSummaryCSV_1200Release

python hcp.py \
  sourcedata/motion/HCPAgingRec \
  derivatives/motion/dataset=HCPAgingRec

python hcp.py \
  sourcedata/motion/HCPDevelopmentRec \
  derivatives/motion/dataset=HCPDevelopmentRec

python abcd.py sourcedata/dcs07/smart/data/abcd/rawdata rawdata/dataset=abcd 
python ukb.py sourcedata/dcs07/smart/data/ukb/rawdata rawdata/dataset=ukb

# spacetop is handled within gather
python gather.py

# events

find \
  /dcs07/smart/data/HCPAgingRec/sourcedata/fmriresults01 \
  -mindepth 5 \
  -maxdepth 5 \
  -type d \
  -name EVs \
  -exec cp -av --parents {} HCPAgingRec/ \;

find \
  /dcs07/smart/data/abcd/rawdata \
  -mindepth 4 \
  -maxdepth 4 \
  -name "*events.tsv" \
  -type f \
  -exec cp -uv --parents {} abcd/ \;
